- name: Deploy K8s
  hosts: k8s
  become: true
  remote_user: vagrant
  tasks:
    - name: create namespace
      k8s:
        name: my-namespace
        api_version: v1
        kind: Namespace
        state: present
 