---
- name: install elinks
  hosts: dev
  become: true
  remote_user: vagrant
  tasks:
    - name: install software
      yum:
        name: elinks
        state: latest
    - name: Install dependencies
      apt:
        name:
            - python3
            - python3-pip
            - python3-setuptools
        state: latest
        update_cache: True
    - name: install docker sdk for python
      pip:
         name: docker
    - name: Log into private registry and force re-authorization
      docker_login:
         registry: https://index.docker.io/v1/
         username: sancyclops
         password: '1111111111'
         reauthorize: yes
    - name: Pull an image
      shell: docker pull sancyclops/san-docker-demo:san-docker-demo
           
    