---
- name: pull docker kube deploy
  hosts: dev
  become: true
  remote_user: vagrant
  tasks:
    - name: Log into private registry and force re-authorization
      docker_login:
         registry: https://index.docker.io/v1/
         username: sancyclops
         password: '1111111111'
         reauthorize: yes
    - name: Pull an image
      shell: docker pull sancyclops/san-docker-demo:san-docker-demo
    - name: Kube Deploy
      shell: docker rm -f test-kube-cont-loc 2> /dev/null || true