---
- name: install elinks
  hosts: dev
  become: true
  remote_user: vagrant
  tasks:
    - name: install software
      yum:
        name: elinks
        state: latest
    - name: install docker sdk for python
      pip:
         name: docker
    - name: Log into private registry and force re-authorization
      docker_login:
         registry: https://index.docker.io/v1/
         username: sancyclops
         password: '1111111111'
         reauthorize: yes
    - name: Pull an image
      shell: docker pull sancyclops/san-docker-demo:san-docker-demo
- name: Deploy K8s
  hosts: k8s
  become: true
  remote_user: vagrant
  tasks:
    - name: create namespace
      k8s:
        name: my-namespace
        api_version: v1
        kind: Namespace
        state: present