---
- name: install elinks
  hosts: dev
  become: true
  remote_user: vagrant
  tasks:
    - name: install software
      yum:
        name: elinks
        state: latest
    - name: install docker sdk for python
      pip:
         name: docker
    - name: pull an image
       docker_image:
          name: sancyclops/san-docker-demo
          tag: latest
          state: present 

 