---
- name: install elinks
  hosts: dev
  become: true
  remote_user: vagrant
  tasks:
    - name: install software
      yum:
        name: elinks
        state: latest

- name: pull an image
  docker_image:
    name: sancyclops/san-docker-demo